### ISSUE TITLE
Calendar subscription: guide and better links

### ISSUE THREAD

**Issue by davidwessman** [fsek/web#549] opened 2016-09-26 09:27 UTC
Right now there is only a `webcal`-link for the different calendar-subscriptions.

I guess it would be nice if we would have some small guide and also a way to get the actual `webcal`-link to add into Google Calendar and such.

**Comment by navro** [comment] 2017-06-18 23:48
Duplicate of #595. Also fixed in #617 by @jessicalastow

**Closed by navro** 2017-06-18 23:48 UTC
